spring:
  application:
    name: weather

  Kafka:
    bootstrapServers: kafka:9092
    producer:
      topic: weather

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://postgres:5432/${spring.application.name}
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        loggerLevel: basic

url:
  forecastAPI: http://forecast:8080

weather-check:
  daily-check-cron: 0 0 18 * * *